name: Test Linux Runner

on:
  workflow_dispatch:
permissions:
  contents: read  

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      
    - name: Test Action
      uses: xf9c/CodeCoverageSummary@master
      with:
        filename: /src/coverage.*.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
